import world.Plant;

public class App {

	@SuppressWarnings("static-access")//ignoring warning generated by Eclipse
	public static void main(String[] args) {

		Plant plant = new Plant();
		
		System.out.println(plant.name);
		System.out.println(plant.ID);
		//System.out.println(plant.type); type is private... only accessible in Plant within the brackets it was created
		
		
		//size is protected and in a different package so below reference won't work
		//System.out.println(plant.size);
		
		//can't access height from Plant class because App is in a different package. 
		//Height has package-level visibility from being created without a modifier.
	}

}
